### ISSUE TITLE
Could not trigger Flow card with id "newUser"

### ISSUE THREAD

**Issue by spkesDE** [spkesDE/com.spkes.telegramNotifications#32]
```
2023-07-05T16:28:41.014Z [err] Error: Could not trigger Flow card with id "newUser": Invalid value for token username. Expected string but got undefined
    at FlowCardTrigger.trigger (/node_modules/@athombv/homey-apps-sdk-v3/lib/FlowCardTrigger.js:52:17)
    at /app/flow/triggers/handleNewUsers.js:28:18
    at /app/node_modules/telegraf/lib/composer.js:378:49
    at /app/node_modules/telegraf/lib/composer.js:167:111
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async execute (/app/node_modules/telegraf/lib/composer.js:485:17)
    at async /app/node_modules/telegraf/lib/composer.js:486:21
    at async execute (/app/node_modules/telegraf/lib/composer.js:485:17)
    at async execute (/app/node_modules/telegraf/lib/composer.js:485:17)
    at async execute (/app/node_modules/telegraf/lib/composer.js:485:17)
```

**Comment by spkesDE** [comment]
Was fixed with c38b415
